# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/abnmt/theater/models/performance/columns.yaml
filter: config_filter.yaml

# Model Class name
modelClass: Abnmt\Theater\Models\Performance

# List Title
title: Управление спектаклями

# Link URL for each record
recordUrl: abnmt/theater/performances/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 100

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
defaultSort:
    column: premiere_date
    direction: desc


# Display checkboxes next to each record
# showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
